UsersBundle\Entity\Euroformac:
    type: entity
    table: euroformac
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        telefono:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
